spring.application.name=Journal
spring.data.mongodb.uri=mongodb+srv://raunak6203958545_db_user:NewMongoDBPass@cluster0.ykdlbfg.mongodb.net/journal
spring.data.mongodb.auto-index-creation=true
spring.main.allow-circular-references=true
server.port=8080
server.servlet.context-path = /journal
